version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      root-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "client"
    commit-message:
      prefix: "chore(client)"
      include: "scope"
    groups:
      client-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "server"
    commit-message:
      prefix: "chore(server)"
      include: "scope"
    groups:
      server-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
